# kkrpc配置
melot:
  kkrpc:
    registryConfig:
      address: zk1.kktv2.com:2181,zk2.kktv2.com:2181,zk3.kktv2.com:2181
      sessionTimeout: 10000
      sessconnTimeout: 30000
    applicationConfig:
      appName: kk-nationalPK-project
      author: sj
      appVersion: 1.0.0
    providerConfig:
      version: 1.0.0
      host: 10.0.*
      port: 30000
      workerThreads: 8
      ioThreads: 8
      queueSize: 8
# elasticJob配置
  elasticJob:
    regCenter:
      serverList: zk1.kktv2.com:2181,zk2.kktv2.com:2181,zk3.kktv2.com:2181
      namespace: api-melot-job
    simpleJob[0]:
      cron: 0/10 * * * * ?
      jobName: setCurrentSeasonConfJob
      refJobName: setCurrentSeasonConfJob
      email: jian.sheng@melot.cn
      host: 10.0.*.*
      tenantIds: 0
    simpleJob[1]:
      cron: 0 0/30 * * * ?
      jobName: giveRewardJob
      refJobName: giveRewardJob
      email: jian.sheng@melot.cn
      host: 10.0.*.*
      tenantIds: 0